### ISSUE TITLE
bitbake core-image-base error

### ISSUE THREAD

**Issue by antoniosap** [MarvellEmbeddedProcessors/marvell-embedded-linux-platform#1]
hello,

just after 'repo sync' i type:
chmod a+x setup-environment
sh setup-environment
MACHINE=clearfog source setup-environment build
bitbake core-image-base

> ERROR: Unable to parse PATH[:=]
> Traceback (most recent call last):
>   File "PATH[:=]", line 1, in <module>
> ExpansionError: Failure expanding variable PATH[:=], expression was ${@os.path.dirname(bb.utils.which(d.getVar('PATH'),'bitbake'))}:${HOSTTOOLS_DIR} which triggered exception TypeError: getVar() takes at least 3 arguments (2 given)
> 
> ERROR: Error parsing configuration files
> Traceback (most recent call last):
>   File "/home/sapuppo/workspace-marvell/sources/bitbake/lib/bb/cookerdata.py", line 258, in CookerDataBuilder.parseBaseConfiguration():
>              try:
>     >            self.parseConfigurationFiles(self.prefiles, self.postfiles)
>              except SyntaxError:
>   File "/home/sapuppo/workspace-marvell/sources/bitbake/lib/bb/cookerdata.py", line 299, in CookerDataBuilder.parseConfigurationFiles(prefiles=[], postfiles=[]):
>                      data = parse_config_file(os.path.join(layer, "conf", "layer.conf"), data)
>     >                data.expandVarref('LAYERDIR')
>      
> AttributeError: 'NoneType' object has no attribute 'expandVarref'

any ideas ?

**Comment by CAnthony015** [comment]
Dear  Antoniosap 

I have the same question , Do you have modified this error ? 
Please help me 

thanks
Edwin

**Comment by antoniosap** [comment]
my experiments on armada is now delayed. 
the repo is unstable.
i think that bring to life commercial products on this core linux is hard.
however hardware is excellent.
