### ISSUE TITLE
setup-environment syntax error

### ISSUE THREAD

**Issue by antoniosap** [MarvellEmbeddedProcessors/marvell-embedded-linux-platform#2]
hello,

every second run of:
MACHINE=clearfog . setup-environment build
i have:
```
Traceback (most recent call last):
  File "sources/base/setup_environment_internal.py", line 628, in <module>
    load_modules()
  File "sources/base/setup_environment_internal.py", line 192, in load_modules
    for module in find_modules():
  File "sources/base/setup_environment_internal.py", line 133, in find_modules
    layers = find_layers()
  File "sources/base/setup_environment_internal.py", line 524, in find_layers
    priority = get_layer_priority(layer_dir)
  File "sources/base/setup_environment_internal.py", line 497, in get_layer_priority
    c.read_conf()
  File "sources/base/setup_environment_internal.py", line 407, in read_conf
    self.conf_data = self._parse_conf(self._read_conf())
  File "sources/base/setup_environment_internal.py", line 382, in _parse_conf
    expr = parse_assignment_expr(line)
  File "sources/base/setup_environment_internal.py", line 319, in parse_assignment_expr
    return (var, op, parse_value(val))
  File "sources/base/setup_environment_internal.py", line 287, in parse_value
    return split_keep_spaces(str(eval(val)))
  File "<string>", line 1
    "${@bb.utils.contains("DISTRO_FEATURES", "x11", "gnome-layer xfce-layer", "", d)}"
                                         ^
SyntaxError: invalid syntax

```

**Comment by netazurh** [comment]
Hi,

Which repo init command do you use?

Thanks,
Neta

**Comment by antoniosap** [comment]
repo init -u https://github.com/MarvellEmbeddedProcessors/marvell-embedded-linux-platform.git -b krogoth
repo sync

**Comment by fbertux** [comment]
Hi @antoniosap 

What distro and version are you using on host machine?

**Comment by otavio** [comment]
@antoniosap for the sake of completeness, bear in mind that Yocto Project 2.1 is expected to work just one few specific Linux distribution releases. You can find the complete list at:

http://www.yoctoproject.org/docs/2.1.2/ref-manual/ref-manual.html#detailed-supported-distros

Your error seems to be related to a not supported Python version, but I may be mistaken.

**Comment by antoniosap** [comment]
```
Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-16.04"
TARGET_SYS        = "arm-marvell-linux-gnueabi"
MACHINE           = "clearfog"
DISTRO            = "eliot-guard"
DISTRO_VERSION    = "2.3"
TUNE_FEATURES     = "arm armv7a vfp  neon        callconvention-hard"
TARGET_FPU        = "hard"
meta-virtualization = "HEAD:db67d896c51145d231d817c76609af762447129a"
meta-ossystems-base = "HEAD:81ba8664b0b3679675d2132bcad1864613486c99"
meta-marvell-distro = "HEAD:eada65443d3ea8f4eda45ccec7c3745d4bc81152"
meta-python       = "HEAD:55c8a76da5dc099a7bc3838495c672140cedb78e"
meta-marvell      = "HEAD:fdbfd764e928f09aa74598a95dd7e9db9d8b7ec1"
meta-oe           
meta-filesystems  = "HEAD:55c8a76da5dc099a7bc3838495c672140cedb78e"
meta              = "HEAD:fb28c54347fcf4957b9b8ee7dee423d859eb7820"
meta-networking   
meta-webserver    = "HEAD:55c8a76da5dc099a7bc3838495c672140cedb78e"
meta-eliot-guard  = "master:aa1576d04ac84de5882bf1228f849e7dca03252e"
```

**Comment by otavio** [comment]
@antoniosap as we mentioned, the Ubuntu 16.04 is not supported. You can use a virtual machine or a Docker container to run a valid version.

**Comment by antoniosap** [comment]
same error on 14.04
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by fbertux** [comment]
@antoniosap 
I see that you're using DISTRO = "eliot-guard", check if these error appears if you run:

```
repo init -u https://github.com/MarvellEmbeddedProcessors/marvell-embedded-linux-platform.git -b krogoth
repo sync
MACHINE=clearfog source setup-environment build
bitbake core-image-minimal
```

Also check if you have all requirements installed https://www.yoctoproject.org/docs/2.1/ref-manual/ref-manual.html#required-packages-for-the-host-development-system

And, this meta-eliot-guard shows DISTRO_VERSION = 2.3, maybe this only works if newer Yocto versions.

**Comment by antoniosap** [comment]
the problem is on upper layers added for custom board.

**Comment by madhav-nadar** [comment]
Any plan to support latest Yocto ? or porting Marvell layers to latest Yocto branch
